In [1]:
import pandas as pd
import numpy as np

In [2]:
lst = [8,5,9,8,5,6,4]
arr1 = pd.Series(lst)

In [3]:
arr1

0    8
1    5
2    9
3    8
4    5
5    6
6    4
dtype: int64

In [5]:
dct1 = {
    'ID': [1,2,3,4,5,6,7,8],
    'Name': ['Ajay','Ajay1','Ajay2','Ajay3','Ajay4','Ajay5','Ajay6','Ajay7']
}
pd.DataFrame(dct1)

   ID   Name
0   1   Ajay
1   2  Ajay1
2   3  Ajay2
3   4  Ajay3
4   5  Ajay4
5   6  Ajay5
6   7  Ajay6
7   8  Ajay7

In [29]:
df1 = pd.read_csv('data.csv')
df1

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [30]:
df1.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [31]:
df1.tail(3)

    Duration          Date  Pulse  Maxpulse  Calories
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [32]:
df1.shape

(32, 5)

In [33]:
list(df1.columns)

['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories']

In [34]:
df1['Duration']

0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64

In [35]:
df1.loc[:,'Duration']

0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64

In [36]:
df1.loc[:,['Duration', 'Date']]

    Duration          Date
0         60  '2020/12/01'
1         60  '2020/12/02'
2         60  '2020/12/03'
3         45  '2020/12/04'
4         45  '2020/12/05'
5         60  '2020/12/06'
6         60  '2020/12/07'
7        450  '2020/12/08'
8         30  '2020/12/09'
9         60  '2020/12/10'
10        60  '2020/12/11'
11        60  '2020/12/12'
12        60  '2020/12/12'
13        60  '2020/12/13'
14        60  '2020/12/14'
15        60  '2020/12/15'
16        60  '2020/12/16'
17        60  '2020/12/17'
18        45  '2020/12/18'
19        60  '2020/12/19'
20        45  '2020/12/20'
21        60  '2020/12/21'
22        45           NaN
23        60  '2020/12/23'
24        45  '2020/12/24'
25        60  '2020/12/25'
26        60      20201226
27        60  '2020/12/27'
28        60  '2020/12/28'
29        60  '2020/12/29'
30        60  '2020/12/30'
31        60  '2020/12/31'

In [37]:
df1.iloc[0]

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [38]:
df1.iloc[[0]]

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1

In [43]:
for i in df1.dtypes:
    print(str(i))

int64
object
int64
int64
float64

In [45]:
df1['Duration'].dtype

dtype('int64')

In [51]:
df1.loc[(df1['Maxpulse'] < 175) & (df1['Maxpulse'] > 125)]

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
21        60  '2020/12/21'    108       131     364.2
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3

In [54]:
df1.columns = ['Durationx', 'Date', 'Pulse', 'Maxpulse', 'Calories']

In [55]:
df1.columns

Index(['Durationx', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [56]:
df1.rename(columns={'Durationx': 'Duration'})

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [59]:
df1.index = df1['Maxpulse']

In [60]:
df1.index

Index([130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 120, 128,
       132, 123, 120, 120, 112, 123, 125, 131, 119, 101, 132, 126, 120, 118,
       132, 132, 129, 115],
      dtype='int64', name='Maxpulse')

In [63]:
df1['Maxpulse'].astype('float64')

Maxpulse
130    130.0
145    145.0
135    135.0
175    175.0
148    148.0
127    127.0
136    136.0
134    134.0
133    133.0
124    124.0
147    147.0
120    120.0
120    120.0
128    128.0
132    132.0
123    123.0
120    120.0
120    120.0
112    112.0
123    123.0
125    125.0
131    131.0
119    119.0
101    101.0
132    132.0
126    126.0
120    120.0
118    118.0
132    132.0
132    132.0
129    129.0
115    115.0
Name: Maxpulse, dtype: float64

In [64]:
df1['Country']  = "India"

In [65]:
df1

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
130              60  '2020/12/01'    110       130     409.1   India
145              60  '2020/12/02'    117       145     479.0   India
135              60  '2020/12/03'    103       135     340.0   India
175              45  '2020/12/04'    109       175     282.4   India
148              45  '2020/12/05'    117       148     406.0   India
127              60  '2020/12/06'    102       127     300.0   India
136              60  '2020/12/07'    110       136     374.0   India
134             450  '2020/12/08'    104       134     253.3   India
133              30  '2020/12/09'    109       133     195.1   India
124              60  '2020/12/10'     98       124     269.0   India
147              60  '2020/12/11'    103       147     329.3   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/12'    100       120     250.7   India
128              60  '2020/12/13'    106       128     345.3   India
132              60  '2020/12/14'    104       132     379.3   India
123              60  '2020/12/15'     98       123     275.0   India
120              60  '2020/12/16'     98       120     215.2   India
120              60  '2020/12/17'    100       120     300.0   India
112              45  '2020/12/18'     90       112       NaN   India
123              60  '2020/12/19'    103       123     323.0   India
125              45  '2020/12/20'     97       125     243.0   India
131              60  '2020/12/21'    108       131     364.2   India
119              45           NaN    100       119     282.0   India
101              60  '2020/12/23'    130       101     300.0   India
132              45  '2020/12/24'    105       132     246.0   India
126              60  '2020/12/25'    102       126     334.5   India
120              60      20201226    100       120     250.0   India
118              60  '2020/12/27'     92       118     241.0   India
132              60  '2020/12/28'    103       132       NaN   India
132              60  '2020/12/29'    100       132     280.0   India
129              60  '2020/12/30'    102       129     380.3   India
115              60  '2020/12/31'     92       115     243.0   India

In [67]:
df1.drop(columns=['Country'])

          Durationx          Date  Pulse  Maxpulse  Calories
Maxpulse
130              60  '2020/12/01'    110       130     409.1
145              60  '2020/12/02'    117       145     479.0
135              60  '2020/12/03'    103       135     340.0
175              45  '2020/12/04'    109       175     282.4
148              45  '2020/12/05'    117       148     406.0
127              60  '2020/12/06'    102       127     300.0
136              60  '2020/12/07'    110       136     374.0
134             450  '2020/12/08'    104       134     253.3
133              30  '2020/12/09'    109       133     195.1
124              60  '2020/12/10'     98       124     269.0
147              60  '2020/12/11'    103       147     329.3
120              60  '2020/12/12'    100       120     250.7
120              60  '2020/12/12'    100       120     250.7
128              60  '2020/12/13'    106       128     345.3
132              60  '2020/12/14'    104       132     379.3
123              60  '2020/12/15'     98       123     275.0
120              60  '2020/12/16'     98       120     215.2
120              60  '2020/12/17'    100       120     300.0
112              45  '2020/12/18'     90       112       NaN
123              60  '2020/12/19'    103       123     323.0
125              45  '2020/12/20'     97       125     243.0
131              60  '2020/12/21'    108       131     364.2
119              45           NaN    100       119     282.0
101              60  '2020/12/23'    130       101     300.0
132              45  '2020/12/24'    105       132     246.0
126              60  '2020/12/25'    102       126     334.5
120              60      20201226    100       120     250.0
118              60  '2020/12/27'     92       118     241.0
132              60  '2020/12/28'    103       132       NaN
132              60  '2020/12/29'    100       132     280.0
129              60  '2020/12/30'    102       129     380.3
115              60  '2020/12/31'     92       115     243.0

In [69]:
df1.drop(index=132)

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
130              60  '2020/12/01'    110       130     409.1   India
145              60  '2020/12/02'    117       145     479.0   India
135              60  '2020/12/03'    103       135     340.0   India
175              45  '2020/12/04'    109       175     282.4   India
148              45  '2020/12/05'    117       148     406.0   India
127              60  '2020/12/06'    102       127     300.0   India
136              60  '2020/12/07'    110       136     374.0   India
134             450  '2020/12/08'    104       134     253.3   India
133              30  '2020/12/09'    109       133     195.1   India
124              60  '2020/12/10'     98       124     269.0   India
147              60  '2020/12/11'    103       147     329.3   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/12'    100       120     250.7   India
128              60  '2020/12/13'    106       128     345.3   India
123              60  '2020/12/15'     98       123     275.0   India
120              60  '2020/12/16'     98       120     215.2   India
120              60  '2020/12/17'    100       120     300.0   India
112              45  '2020/12/18'     90       112       NaN   India
123              60  '2020/12/19'    103       123     323.0   India
125              45  '2020/12/20'     97       125     243.0   India
131              60  '2020/12/21'    108       131     364.2   India
119              45           NaN    100       119     282.0   India
101              60  '2020/12/23'    130       101     300.0   India
126              60  '2020/12/25'    102       126     334.5   India
120              60      20201226    100       120     250.0   India
118              60  '2020/12/27'     92       118     241.0   India
129              60  '2020/12/30'    102       129     380.3   India
115              60  '2020/12/31'     92       115     243.0   India

In [82]:
df1.sort_values(by='Calories')

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
133              30  '2020/12/09'    109       133     195.1   India
120              60  '2020/12/16'     98       120     215.2   India
118              60  '2020/12/27'     92       118     241.0   India
115              60  '2020/12/31'     92       115     243.0   India
125              45  '2020/12/20'     97       125     243.0   India
132              45  '2020/12/24'    105       132     246.0   India
120              60      20201226    100       120     250.0   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/12'    100       120     250.7   India
134             450  '2020/12/08'    104       134     253.3   India
124              60  '2020/12/10'     98       124     269.0   India
123              60  '2020/12/15'     98       123     275.0   India
132              60  '2020/12/29'    100       132     280.0   India
119              45           NaN    100       119     282.0   India
175              45  '2020/12/04'    109       175     282.4   India
127              60  '2020/12/06'    102       127     300.0   India
120              60  '2020/12/17'    100       120     300.0   India
101              60  '2020/12/23'    130       101     300.0   India
123              60  '2020/12/19'    103       123     323.0   India
147              60  '2020/12/11'    103       147     329.3   India
126              60  '2020/12/25'    102       126     334.5   India
135              60  '2020/12/03'    103       135     340.0   India
128              60  '2020/12/13'    106       128     345.3   India
131              60  '2020/12/21'    108       131     364.2   India
136              60  '2020/12/07'    110       136     374.0   India
132              60  '2020/12/14'    104       132     379.3   India
129              60  '2020/12/30'    102       129     380.3   India
148              45  '2020/12/05'    117       148     406.0   India
130              60  '2020/12/01'    110       130     409.1   India
145              60  '2020/12/02'    117       145     479.0   India
112              45  '2020/12/18'     90       112       NaN   India
132              60  '2020/12/28'    103       132       NaN   India

In [84]:
df1.sort_values(by='Pulse', ascending=False)

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
101              60  '2020/12/23'    130       101     300.0   India
145              60  '2020/12/02'    117       145     479.0   India
148              45  '2020/12/05'    117       148     406.0   India
136              60  '2020/12/07'    110       136     374.0   India
130              60  '2020/12/01'    110       130     409.1   India
175              45  '2020/12/04'    109       175     282.4   India
133              30  '2020/12/09'    109       133     195.1   India
131              60  '2020/12/21'    108       131     364.2   India
128              60  '2020/12/13'    106       128     345.3   India
132              45  '2020/12/24'    105       132     246.0   India
132              60  '2020/12/14'    104       132     379.3   India
134             450  '2020/12/08'    104       134     253.3   India
123              60  '2020/12/19'    103       123     323.0   India
135              60  '2020/12/03'    103       135     340.0   India
147              60  '2020/12/11'    103       147     329.3   India
132              60  '2020/12/28'    103       132       NaN   India
127              60  '2020/12/06'    102       127     300.0   India
129              60  '2020/12/30'    102       129     380.3   India
126              60  '2020/12/25'    102       126     334.5   India
120              60  '2020/12/12'    100       120     250.7   India
132              60  '2020/12/29'    100       132     280.0   India
120              60      20201226    100       120     250.0   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/17'    100       120     300.0   India
119              45           NaN    100       119     282.0   India
124              60  '2020/12/10'     98       124     269.0   India
123              60  '2020/12/15'     98       123     275.0   India
120              60  '2020/12/16'     98       120     215.2   India
125              45  '2020/12/20'     97       125     243.0   India
118              60  '2020/12/27'     92       118     241.0   India
115              60  '2020/12/31'     92       115     243.0   India
112              45  '2020/12/18'     90       112       NaN   India

In [85]:
df1.sort_values(by=['Pulse', 'Calories'])

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
112              45  '2020/12/18'     90       112       NaN   India
118              60  '2020/12/27'     92       118     241.0   India
115              60  '2020/12/31'     92       115     243.0   India
125              45  '2020/12/20'     97       125     243.0   India
120              60  '2020/12/16'     98       120     215.2   India
124              60  '2020/12/10'     98       124     269.0   India
123              60  '2020/12/15'     98       123     275.0   India
120              60      20201226    100       120     250.0   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/12'    100       120     250.7   India
132              60  '2020/12/29'    100       132     280.0   India
119              45           NaN    100       119     282.0   India
120              60  '2020/12/17'    100       120     300.0   India
127              60  '2020/12/06'    102       127     300.0   India
126              60  '2020/12/25'    102       126     334.5   India
129              60  '2020/12/30'    102       129     380.3   India
123              60  '2020/12/19'    103       123     323.0   India
147              60  '2020/12/11'    103       147     329.3   India
135              60  '2020/12/03'    103       135     340.0   India
132              60  '2020/12/28'    103       132       NaN   India
134             450  '2020/12/08'    104       134     253.3   India
132              60  '2020/12/14'    104       132     379.3   India
132              45  '2020/12/24'    105       132     246.0   India
128              60  '2020/12/13'    106       128     345.3   India
131              60  '2020/12/21'    108       131     364.2   India
133              30  '2020/12/09'    109       133     195.1   India
175              45  '2020/12/04'    109       175     282.4   India
136              60  '2020/12/07'    110       136     374.0   India
130              60  '2020/12/01'    110       130     409.1   India
148              45  '2020/12/05'    117       148     406.0   India
145              60  '2020/12/02'    117       145     479.0   India
101              60  '2020/12/23'    130       101     300.0   India

In [86]:
df1.sort_values(by=['Pulse', 'Calories'], ascending=[True, False])

          Durationx          Date  Pulse  Maxpulse  Calories Country
Maxpulse
112              45  '2020/12/18'     90       112       NaN   India
115              60  '2020/12/31'     92       115     243.0   India
118              60  '2020/12/27'     92       118     241.0   India
125              45  '2020/12/20'     97       125     243.0   India
123              60  '2020/12/15'     98       123     275.0   India
124              60  '2020/12/10'     98       124     269.0   India
120              60  '2020/12/16'     98       120     215.2   India
120              60  '2020/12/17'    100       120     300.0   India
119              45           NaN    100       119     282.0   India
132              60  '2020/12/29'    100       132     280.0   India
120              60  '2020/12/12'    100       120     250.7   India
120              60  '2020/12/12'    100       120     250.7   India
120              60      20201226    100       120     250.0   India
129              60  '2020/12/30'    102       129     380.3   India
126              60  '2020/12/25'    102       126     334.5   India
127              60  '2020/12/06'    102       127     300.0   India
135              60  '2020/12/03'    103       135     340.0   India
147              60  '2020/12/11'    103       147     329.3   India
123              60  '2020/12/19'    103       123     323.0   India
132              60  '2020/12/28'    103       132       NaN   India
132              60  '2020/12/14'    104       132     379.3   India
134             450  '2020/12/08'    104       134     253.3   India
132              45  '2020/12/24'    105       132     246.0   India
128              60  '2020/12/13'    106       128     345.3   India
131              60  '2020/12/21'    108       131     364.2   India
175              45  '2020/12/04'    109       175     282.4   India
133              30  '2020/12/09'    109       133     195.1   India
130              60  '2020/12/01'    110       130     409.1   India
136              60  '2020/12/07'    110       136     374.0   India
145              60  '2020/12/02'    117       145     479.0   India
148              45  '2020/12/05'    117       148     406.0   India
101              60  '2020/12/23'    130       101     300.0   India

In [98]:
df1.rename(columns={'Durationx': 'Duration'}, inplace=True)

In [105]:
df1.fillna(5).head(5)

          Duration          Date  Pulse  Maxpulse  Calories Country
Maxpulse
130             60  '2020/12/01'    110       130     409.1   India
145             60  '2020/12/02'    117       145     479.0   India
135             60  '2020/12/03'    103       135     340.0   India
175             45  '2020/12/04'    109       175     282.4   India
148             45  '2020/12/05'    117       148     406.0   India

In [109]:
df1.ffill()

          Duration          Date  Pulse  Maxpulse  Calories Country
Maxpulse
130             60  '2020/12/01'    110       130     409.1   India
145             60  '2020/12/02'    117       145     479.0   India
135             60  '2020/12/03'    103       135     340.0   India
175             45  '2020/12/04'    109       175     282.4   India
148             45  '2020/12/05'    117       148     406.0   India
127             60  '2020/12/06'    102       127     300.0   India
136             60  '2020/12/07'    110       136     374.0   India
134            450  '2020/12/08'    104       134     253.3   India
133             30  '2020/12/09'    109       133     195.1   India
124             60  '2020/12/10'     98       124     269.0   India
147             60  '2020/12/11'    103       147     329.3   India
120             60  '2020/12/12'    100       120     250.7   India
120             60  '2020/12/12'    100       120     250.7   India
128             60  '2020/12/13'    106       128     345.3   India
132             60  '2020/12/14'    104       132     379.3   India
123             60  '2020/12/15'     98       123     275.0   India
120             60  '2020/12/16'     98       120     215.2   India
120             60  '2020/12/17'    100       120     300.0   India
112             45  '2020/12/18'     90       112     300.0   India
123             60  '2020/12/19'    103       123     323.0   India
125             45  '2020/12/20'     97       125     243.0   India
131             60  '2020/12/21'    108       131     364.2   India
119             45  '2020/12/21'    100       119     282.0   India
101             60  '2020/12/23'    130       101     300.0   India
132             45  '2020/12/24'    105       132     246.0   India
126             60  '2020/12/25'    102       126     334.5   India
120             60      20201226    100       120     250.0   India
118             60  '2020/12/27'     92       118     241.0   India
132             60  '2020/12/28'    103       132     241.0   India
132             60  '2020/12/29'    100       132     280.0   India
129             60  '2020/12/30'    102       129     380.3   India
115             60  '2020/12/31'     92       115     243.0   India

In [110]:
df1.bfill()

          Duration          Date  Pulse  Maxpulse  Calories Country
Maxpulse
130             60  '2020/12/01'    110       130     409.1   India
145             60  '2020/12/02'    117       145     479.0   India
135             60  '2020/12/03'    103       135     340.0   India
175             45  '2020/12/04'    109       175     282.4   India
148             45  '2020/12/05'    117       148     406.0   India
127             60  '2020/12/06'    102       127     300.0   India
136             60  '2020/12/07'    110       136     374.0   India
134            450  '2020/12/08'    104       134     253.3   India
133             30  '2020/12/09'    109       133     195.1   India
124             60  '2020/12/10'     98       124     269.0   India
147             60  '2020/12/11'    103       147     329.3   India
120             60  '2020/12/12'    100       120     250.7   India
120             60  '2020/12/12'    100       120     250.7   India
128             60  '2020/12/13'    106       128     345.3   India
132             60  '2020/12/14'    104       132     379.3   India
123             60  '2020/12/15'     98       123     275.0   India
120             60  '2020/12/16'     98       120     215.2   India
120             60  '2020/12/17'    100       120     300.0   India
112             45  '2020/12/18'     90       112     323.0   India
123             60  '2020/12/19'    103       123     323.0   India
125             45  '2020/12/20'     97       125     243.0   India
131             60  '2020/12/21'    108       131     364.2   India
119             45  '2020/12/23'    100       119     282.0   India
101             60  '2020/12/23'    130       101     300.0   India
132             45  '2020/12/24'    105       132     246.0   India
126             60  '2020/12/25'    102       126     334.5   India
120             60      20201226    100       120     250.0   India
118             60  '2020/12/27'     92       118     241.0   India
132             60  '2020/12/28'    103       132     280.0   India
132             60  '2020/12/29'    100       132     280.0   India
129             60  '2020/12/30'    102       129     380.3   India
115             60  '2020/12/31'     92       115     243.0   India

In [111]:
df1.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [120]:
df1['Maxpulse'].nunique()

24

In [121]:
df1['Maxpulse'].unique()

array([130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 128,
       132, 123, 112, 125, 131, 119, 101, 126, 118, 129, 115])

In [124]:
df1['Maxpulse'].value_counts()

Maxpulse
120    5
132    4
123    2
130    1
148    1
145    1
135    1
175    1
134    1
136    1
127    1
133    1
147    1
124    1
128    1
112    1
125    1
131    1
119    1
101    1
126    1
118    1
129    1
115    1
Name: count, dtype: int64

In [127]:
df1.index = pd.Series(np.arange(0, len(df1)))

In [128]:
df1.value_counts()

Duration  Date          Pulse  Maxpulse  Calories  Country
60        '2020/12/12'  100    120       250.7     India      2
30        '2020/12/09'  109    133       195.1     India      1
45        '2020/12/05'  117    148       406.0     India      1
          '2020/12/04'  109    175       282.4     India      1
          '2020/12/24'  105    132       246.0     India      1
60        '2020/12/01'  110    130       409.1     India      1
          '2020/12/02'  117    145       479.0     India      1
          '2020/12/03'  103    135       340.0     India      1
          '2020/12/06'  102    127       300.0     India      1
          '2020/12/07'  110    136       374.0     India      1
          '2020/12/10'  98     124       269.0     India      1
45        '2020/12/20'  97     125       243.0     India      1
60        '2020/12/11'  103    147       329.3     India      1
          '2020/12/13'  106    128       345.3     India      1
          '2020/12/14'  104    132       379.3     India      1
          '2020/12/15'  98     123       275.0     India      1
          '2020/12/16'  98     120       215.2     India      1
          '2020/12/17'  100    120       300.0     India      1
          '2020/12/19'  103    123       323.0     India      1
          '2020/12/21'  108    131       364.2     India      1
          '2020/12/23'  130    101       300.0     India      1
          '2020/12/25'  102    126       334.5     India      1
          '2020/12/27'  92     118       241.0     India      1
          '2020/12/29'  100    132       280.0     India      1
          '2020/12/30'  102    129       380.3     India      1
          '2020/12/31'  92     115       243.0     India      1
          20201226      100    120       250.0     India      1
450       '2020/12/08'  104    134       253.3     India      1
Name: count, dtype: int64

In [132]:
df1['Calories'].value_counts()

Calories
300.0    3
250.7    2
243.0    2
340.0    1
479.0    1
406.0    1
374.0    1
253.3    1
282.4    1
409.1    1
269.0    1
195.1    1
345.3    1
329.3    1
379.3    1
275.0    1
215.2    1
323.0    1
364.2    1
282.0    1
246.0    1
334.5    1
250.0    1
241.0    1
280.0    1
380.3    1
Name: count, dtype: int64

In [134]:
df1['New Col'] = df1['Pulse'].apply(lambda x : x ** 2)

In [136]:
df1['Total'] = df1.apply(lambda x : x['Calories'] + x['Maxpulse'], axis=1)

In [143]:
df1[(df1['Pulse'] > 110) & (df1['Calories'] < 400)]

    Duration          Date  Pulse  Maxpulse  Calories Country  New Col  Total
23        60  '2020/12/23'    130       101     300.0   India    16900  401.0

In [148]:
 groups = df1.groupby(by=['Calories'])

In [157]:
print(groups['Country'])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x0000025F4D03E0D0>

In [154]:
groups['Duration'].mean()

Calories
195.1     30.0
215.2     60.0
241.0     60.0
243.0     52.5
246.0     45.0
250.0     60.0
250.7     60.0
253.3    450.0
269.0     60.0
275.0     60.0
280.0     60.0
282.0     45.0
282.4     45.0
300.0     60.0
323.0     60.0
329.3     60.0
334.5     60.0
340.0     60.0
345.3     60.0
364.2     60.0
374.0     60.0
379.3     60.0
380.3     60.0
406.0     45.0
409.1     60.0
479.0     60.0
Name: Duration, dtype: float64

In [160]:
df1.describe()

,Duration,Pulse,Maxpulse,Calories,New Col,Total
count,32.000000,32.000000,32.000000,30.000000,32.000000,30.000000
mean,68.437500,103.500000,128.500000,304.680000,10771.687500,433.613333
std,70.039591,7.832933,12.998759,66.003779,1698.843391,71.718043
min,30.000000,90.000000,101.000000,195.100000,8100.000000,328.100000
25%,60.000000,100.000000,120.000000,250.700000,10000.000000,372.525000
50%,60.000000,102.500000,127.500000,291.200000,10506.500000,416.000000
75%,60.000000,106.500000,132.250000,343.975000,11343.000000,475.975000
max,450.000000,130.000000,175.000000,479.000000,16900.000000,624.000000