In [2]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'2.3.2'

In [5]:
l = [54,234,45-1,43,-1,'val']

In [6]:
print(l)

[54, 234, 44, 43, -1, 'val']

In [7]:
sr1 = pd.Series(l)

In [8]:
sr1

0     54
1    234
2     44
3     43
4     -1
5    val
dtype: object

In [9]:
type(sr1)

pandas.core.series.Series

In [10]:
sr2 = pd.Series([432,54,2,52,43,3525,43245])
sr2

0      432
1       54
2        2
3       52
4       43
5     3525
6    43245
dtype: int64

In [11]:
sr3 = pd.Series([432,54,2,52,43,3525,43245], index=[5,43,543,5434,1,53,5432])
sr3

5         432
43         54
543         2
5434       52
1          43
53       3525
5432    43245
dtype: int64

In [12]:
sr3 = pd.Series([432,54,2,52,43,3525,43245], index=[5,43,543,5434,1,53,5432], dtype=float)
sr3

5         432.0
43         54.0
543         2.0
5434       52.0
1          43.0
53       3525.0
5432    43245.0
dtype: float64

In [13]:
sr4 = pd.Series([432,54,2,52,43,3525,43245], index=[5,43,543,5434,1,53,5432], dtype=float, name="Data Values")
sr4

5         432.0
43         54.0
543         2.0
5434       52.0
1          43.0
53       3525.0
5432    43245.0
Name: Data Values, dtype: float64

In [14]:
scaler_s = pd.Series(0.5)
scaler_s

0    0.5
dtype: float64

In [15]:
scaler_s = pd.Series(0.5, index=[1,2,3])
scaler_s

1    0.5
2    0.5
3    0.5
dtype: float64

In [16]:
scaler_s = pd.Series({'a': 12, 'b': 16, 'c': 18})
scaler_s

a    12
b    16
c    18
dtype: int64

In [17]:
scaler_s['a']

np.int64(12)

In [18]:
scaler_s.iloc[0]

np.int64(12)

In [19]:
scaler_s.iloc[1:4]

b    16
c    18
dtype: int64

In [20]:
max(scaler_s)

18

In [21]:
min(scaler_s)

12

In [22]:
scaler_s[scaler_s > 1]

a    12
b    16
c    18
dtype: int64

In [23]:
s5 = pd.Series([1,2,3,4,5])
s5

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
s4 = pd.Series([4,5,4,3,3])
s5 + s4

0    5
1    7
2    7
3    7
4    8
dtype: int64

In [25]:
pd.Series([4,6,2]) + s5

0    5.0
1    8.0
2    5.0
3    NaN
4    NaN
dtype: float64

In [26]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [27]:
lst = ['a', 'b', 'c']
lst

['a', 'b', 'c']

In [28]:
df1 = pd.DataFrame(lst)

In [29]:
df1

   0
0  a
1  b
2  c

In [30]:
ls_of_ls = [[1,2,3], [4,5,6], [7,8,9]]
ls_of_ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
df2 = pd.DataFrame(ls_of_ls)

In [32]:
df2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [33]:
dct = {
    '1D': [12,314,234,53,4]
}
df3 = pd.DataFrame(dct)

In [34]:
df3

    1D
0   12
1  314
2  234
3   53
4    4

In [35]:
dct1 = {
    '1D': [12,314,234,53,4],
    'XD': [12,34,234,53,4]
}
df4 = pd.DataFrame(dct1)

In [36]:
df4

    1D   XD
0   12   12
1  314   34
2  234  234
3   53   53
4    4    4

In [37]:
dct2 = [{'a': 1, 'b': 2}, {'a': 4, 'b': 8}]

In [38]:
dct2

[{'a': 1, 'b': 2}, {'a': 4, 'b': 8}]

In [39]:
df5 = pd.DataFrame(dct2)
df5

   a  b
0  1  2
1  4  8

In [40]:
dct3 = [{'a': 1, 'b': 2}, {'a': 4, 'b': 8, 'c': 1}]
pd.DataFrame(dct3)

   a  b    c
0  1  2  NaN
1  4  8  1.0

In [41]:
dict_sr = [pd.Series([1,2,3]), pd.Series([4,5,6])]
dict_sr

[0    1
 1    2
 2    3
 dtype: int64,
 0    4
 1    5
 2    6
 dtype: int64]

In [42]:
pd.DataFrame(dict_sr)

   0  1  2
0  1  2  3
1  4  5  6

In [43]:
pd.read_csv('data.csv')

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [44]:
import os
os.getcwd()

'C:\\Users\\ajaya'

In [45]:
data = pd.read_csv('data.csv')

In [46]:
data.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [47]:
type(data)

pandas.core.frame.DataFrame

In [48]:
data.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [49]:
d1 = pd.read_csv('data.csv', nrows=5)
d1

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [50]:
pd.read_csv('data.csv', usecols=['Date', 'Calories'], nrows=5)

           Date  Calories
0  '2020/12/01'     409.1
1  '2020/12/02'     479.0
2  '2020/12/03'     340.0
3  '2020/12/04'     282.4
4  '2020/12/05'     406.0

In [51]:
pd.read_csv('data.csv', usecols=[2,3], nrows=5)

   Pulse  Maxpulse
0    110       130
1    117       145
2    103       135
3    109       175
4    117       148

In [52]:
pd.read_csv('data.csv',  nrows=5, skiprows=1)

   60  '2020/12/01'  110  130  409.1
0  60  '2020/12/02'  117  145  479.0
1  60  '2020/12/03'  103  135  340.0
2  45  '2020/12/04'  109  175  282.4
3  45  '2020/12/05'  117  148  406.0
4  60  '2020/12/06'  102  127  300.0

In [53]:
pd.read_csv('data.csv',  nrows=5, skiprows=2)

   60  '2020/12/02'  117  145  479.0
0  60  '2020/12/03'  103  135  340.0
1  45  '2020/12/04'  109  175  282.4
2  45  '2020/12/05'  117  148  406.0
3  60  '2020/12/06'  102  127  300.0
4  60  '2020/12/07'  110  136  374.0

In [54]:
pd.read_csv('data.csv',  nrows=5, skiprows=[0,2])

   60  '2020/12/01'  110  130  409.1
0  60  '2020/12/03'  103  135  340.0
1  45  '2020/12/04'  109  175  282.4
2  45  '2020/12/05'  117  148  406.0
3  60  '2020/12/06'  102  127  300.0
4  60  '2020/12/07'  110  136  374.0

In [55]:
pd.read_csv('data.csv',  nrows=5, skiprows=[5])

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        60  '2020/12/06'    102       127     300.0

In [56]:
pd.read_csv('data.csv',  nrows=5, skiprows=[5], index_col='Date')

              Duration  Pulse  Maxpulse  Calories
Date
'2020/12/01'        60    110       130     409.1
'2020/12/02'        60    117       145     479.0
'2020/12/03'        60    103       135     340.0
'2020/12/04'        45    109       175     282.4
'2020/12/06'        60    102       127     300.0

In [57]:
pd.read_csv('data.csv',  nrows=5, skiprows=[5], index_col=3)

          Duration          Date  Pulse  Calories
Maxpulse
130             60  '2020/12/01'    110     409.1
145             60  '2020/12/02'    117     479.0
135             60  '2020/12/03'    103     340.0
175             45  '2020/12/04'    109     282.4
127             60  '2020/12/06'    102     300.0

In [58]:
pd.read_csv('data.csv', header=0, nrows=5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [59]:
pd.read_csv('data.csv', header=None, nrows=5)

          0             1      2         3         4
0  Duration          Date  Pulse  Maxpulse  Calories
1        60  '2020/12/01'    110       130     409.1
2        60  '2020/12/02'    117       145     479.0
3        60  '2020/12/03'    103       135     340.0
4        45  '2020/12/04'    109       175     282.4

In [60]:
df2 = pd.read_csv('data.csv', header=None, nrows=5)

In [61]:
df2.columns = [f"xd{i}" for i in range(len(df2.columns))]

In [62]:
df2

        xd0           xd1    xd2       xd3       xd4
0  Duration          Date  Pulse  Maxpulse  Calories
1        60  '2020/12/01'    110       130     409.1
2        60  '2020/12/02'    117       145     479.0
3        60  '2020/12/03'    103       135     340.0
4        45  '2020/12/04'    109       175     282.4

In [63]:
df2 = pd.read_csv('data.csv', names=[i**2 for i in range(5)], nrows=5)
df2

         0             1      4         9         16
0  Duration          Date  Pulse  Maxpulse  Calories
1        60  '2020/12/01'    110       130     409.1
2        60  '2020/12/02'    117       145     479.0
3        60  '2020/12/03'    103       135     340.0
4        45  '2020/12/04'    109       175     282.4

In [64]:
df2 = pd.read_csv('data.csv', nrows=5, dtype={'Duration': 'float64'})
df2

   Duration          Date  Pulse  Maxpulse  Calories
0      60.0  '2020/12/01'    110       130     409.1
1      60.0  '2020/12/02'    117       145     479.0
2      60.0  '2020/12/03'    103       135     340.0
3      45.0  '2020/12/04'    109       175     282.4
4      45.0  '2020/12/05'    117       148     406.0

In [65]:
df2['Random'] = pd.Series(['Yes' for i in range(len(df2))])
df2.loc[5:10, 'Random'] = "No"

In [66]:
df2.to_csv('data2.csv', index=False)

In [67]:
df3 = pd.read_csv('data2.csv', true_values=['Yes'], false_values=['No'])
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
0      60.0  '2020/12/01'    110       130     409.1    True
1      60.0  '2020/12/02'    117       145     479.0    True
2      60.0  '2020/12/03'    103       135     340.0    True
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [110]:
df3 = pd.read_csv('data2.csv', true_values=['Yes'], false_values=['No'], na_values=['No'])
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
0      60.0  '2020/12/01'    110       130     409.1    True
1      60.0  '2020/12/02'    117       145     479.0    True
2      60.0  '2020/12/03'    103       135     340.0    True
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [111]:
df3 = pd.read_csv('data2.csv', true_values=['Yes'], false_values=['No'], na_values={'Random': 'No', 'Duration': 60}, nrows=25)
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
1       NaN  '2020/12/02'    117       145     479.0    True
2       NaN  '2020/12/03'    103       135     340.0    True
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [3]:
df3 = pd.read_csv('data2.csv', true_values=['Yes'], false_values=['No'], na_values={'Random': 'No', 'Duration': 60}, nrows=25, na_filter=True)
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
1       NaN  '2020/12/02'    117       145     479.0    True
2       NaN  '2020/12/03'    103       135     340.0    True
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [71]:
df3.isnull()

   Duration   Date  Pulse  Maxpulse  Calories  Random
0      True  False  False     False     False   False
1      True  False  False     False     False   False
2      True  False  False     False     False   False
3     False  False  False     False     False   False
4     False  False  False     False     False   False

In [72]:
df3.isnull().sum()

Duration    3
Date        0
Pulse       0
Maxpulse    0
Calories    0
Random      0
dtype: int64

In [73]:
df3.isnull().sum().sum()

np.int64(3)

In [74]:
df3.isnull().sum()

Duration    3
Date        0
Pulse       0
Maxpulse    0
Calories    0
Random      0
dtype: int64

In [75]:
df3.notnull()

   Duration  Date  Pulse  Maxpulse  Calories  Random
0     False  True   True      True      True    True
1     False  True   True      True      True    True
2     False  True   True      True      True    True
3      True  True   True      True      True    True
4      True  True   True      True      True    True

In [76]:
df3.notnull().sum()

Duration    2
Date        5
Pulse       5
Maxpulse    5
Calories    5
Random      5
dtype: int64

In [77]:
df3.notnull().sum().sum()

np.int64(27)

In [78]:
df4 = pd.Series([4,2,5,7,4,2,np.nan])

In [79]:
df4.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [80]:
df4.dropna()

0    4.0
1    2.0
2    5.0
3    7.0
4    4.0
5    2.0
dtype: float64

In [81]:
df4.dropna(axis=0)

0    4.0
1    2.0
2    5.0
3    7.0
4    4.0
5    2.0
dtype: float64

In [82]:
df3.dropna(axis=1)

           Date  Pulse  Maxpulse  Calories  Random
0  '2020/12/01'    110       130     409.1    True
1  '2020/12/02'    117       145     479.0    True
2  '2020/12/03'    103       135     340.0    True
3  '2020/12/04'    109       175     282.4    True
4  '2020/12/05'    117       148     406.0    True

In [83]:
df3.dropna(how='all')

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
1       NaN  '2020/12/02'    117       145     479.0    True
2       NaN  '2020/12/03'    103       135     340.0    True
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [84]:
df3.dropna(how='any')

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [85]:
df3.dropna(thresh=6)

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [86]:
df3.dropna(subset=['Duration'])

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [87]:
df3.dropna(inplace=True)

In [88]:
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [89]:
df3

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [90]:
df3.fillna(0)

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [91]:
df3.fillna({'Duration': 999, 'Random': 'XD'})

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [92]:
df3.ffill().bfill()

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [93]:
df3.fillna(method='pad')

C:\Users\ajaya\AppData\Local\Temp\ipykernel_4652\2392179455.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method='pad')

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [94]:
df3.bfill(axis=1)

  Duration          Date Pulse Maxpulse Calories Random
3     45.0  '2020/12/04'   109      175    282.4   True
4     45.0  '2020/12/05'   117      148    406.0   True

In [95]:
df3.replace(True, "xd")

   Duration          Date  Pulse  Maxpulse  Calories Random
3      45.0  '2020/12/04'    109       175     282.4     xd
4      45.0  '2020/12/05'    117       148     406.0     xd

In [96]:
df3.replace([130,135], [99,999])

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [97]:
df3.replace({'Duration': np.nan, 'Calories': np.nan}, None)

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [98]:
df3.replace('\d\d\d', 700, regex=True)

C:\Users\ajaya\AppData\Local\Temp\ipykernel_4652\2479844212.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3.replace('\d\d\d', 700, regex=True)

   Duration  Date  Pulse  Maxpulse  Calories  Random
3      45.0   700    109       175     282.4    True
4      45.0   700    117       148     406.0    True

In [99]:
df3['Calories'].astype(str)
df3.replace({'Calories': '^\d{3}\.\d'}, None, regex=True)

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [100]:
df3.replace(True, "Lol", inplace=True)

In [101]:
df3

   Duration          Date  Pulse  Maxpulse  Calories Random
3      45.0  '2020/12/04'    109       175     282.4    Lol
4      45.0  '2020/12/05'    117       148     406.0    Lol

In [102]:
df3.interpolate()

C:\Users\ajaya\AppData\Local\Temp\ipykernel_4652\1273901375.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df3.interpolate()

   Duration          Date  Pulse  Maxpulse  Calories Random
3      45.0  '2020/12/04'    109       175     282.4    Lol
4      45.0  '2020/12/05'    117       148     406.0    Lol

In [103]:
df3['Duration']

3    45.0
4    45.0
Name: Duration, dtype: float64

In [104]:
df3.loc[4]

Duration            45.0
Date        '2020/12/05'
Pulse                117
Maxpulse             148
Calories           406.0
Random               Lol
Name: 4, dtype: object

In [105]:
df3.loc[4, 'Duration']

np.float64(45.0)

In [115]:
df3.loc[4:8, 'Duration']

4    45.0
Name: Duration, dtype: float64

In [122]:
df3.loc[[0,1,4]]

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
1       NaN  '2020/12/02'    117       145     479.0    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [123]:
df3.loc[[0,1,4], 'Duration']

0     NaN
1     NaN
4    45.0
Name: Duration, dtype: float64

In [133]:
df3.loc[[False, False, False, True, True]]

   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [145]:
df3.loc[df3['Pulse'] > 109, ['Date', 'Random']]

           Date  Random
0  '2020/12/01'    True
1  '2020/12/02'    True
4  '2020/12/05'    True

In [146]:
df3.iloc[0]

Duration             NaN
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Random              True
Name: 0, dtype: object

In [147]:
df3.iloc[[0]]

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True

In [150]:
df3[['Duration']]

   Duration
0       NaN
1       NaN
2       NaN
3      45.0
4      45.0

In [151]:
df3.loc[:, 'Pulse']

0    110
1    117
2    103
3    109
4    117
Name: Pulse, dtype: int64

In [154]:
df3.iloc[:, 'Pulse']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [157]:
df3.iloc[[0, 1]]

0    110
1    117
Name: Pulse, dtype: int64

In [4]:
df3.iloc[[True, True, False, False, True]]

   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
1       NaN  '2020/12/02'    117       145     479.0    True
4      45.0  '2020/12/05'    117       148     406.0    True

In [18]:
df3p = df3.groupby(by='Maxpulse')
df3p.groups

{130: [0], 135: [2], 145: [1], 148: [4], 175: [3]}

In [16]:
df4p = df3.groupby(['Date', 'Maxpulse'])

In [17]:
df4p.groups

{(''2020/12/01'', 130): [0], (''2020/12/02'', 145): [1], (''2020/12/03'', 135): [2], (''2020/12/04'', 175): [3], (''2020/12/05'', 148): [4]}

In [20]:
for section, x in df4p:
    print(section)
    print(x)

("'2020/12/01'", np.int64(130))
   Duration          Date  Pulse  Maxpulse  Calories  Random
0       NaN  '2020/12/01'    110       130     409.1    True
("'2020/12/02'", np.int64(145))
   Duration          Date  Pulse  Maxpulse  Calories  Random
1       NaN  '2020/12/02'    117       145     479.0    True
("'2020/12/03'", np.int64(135))
   Duration          Date  Pulse  Maxpulse  Calories  Random
2       NaN  '2020/12/03'    103       135     340.0    True
("'2020/12/04'", np.int64(175))
   Duration          Date  Pulse  Maxpulse  Calories  Random
3      45.0  '2020/12/04'    109       175     282.4    True
("'2020/12/05'", np.int64(148))
   Duration          Date  Pulse  Maxpulse  Calories  Random
4      45.0  '2020/12/05'    117       148     406.0    True

In [22]:
list(df3p)

[(130,
     Duration          Date  Pulse  Maxpulse  Calories  Random
  0       NaN  '2020/12/01'    110       130     409.1    True),
 (135,
     Duration          Date  Pulse  Maxpulse  Calories  Random
  2       NaN  '2020/12/03'    103       135     340.0    True),
 (145,
     Duration          Date  Pulse  Maxpulse  Calories  Random
  1       NaN  '2020/12/02'    117       145     479.0    True),
 (148,
     Duration          Date  Pulse  Maxpulse  Calories  Random
  4      45.0  '2020/12/05'    117       148     406.0    True),
 (175,
     Duration          Date  Pulse  Maxpulse  Calories  Random
  3      45.0  '2020/12/04'    109       175     282.4    True)]

In [24]:
dict(list(df4p))

{("'2020/12/01'",
  np.int64(130)):    Duration          Date  Pulse  Maxpulse  Calories  Random
 0       NaN  '2020/12/01'    110       130     409.1    True,
 ("'2020/12/02'",
  np.int64(145)):    Duration          Date  Pulse  Maxpulse  Calories  Random
 1       NaN  '2020/12/02'    117       145     479.0    True,
 ("'2020/12/03'",
  np.int64(135)):    Duration          Date  Pulse  Maxpulse  Calories  Random
 2       NaN  '2020/12/03'    103       135     340.0    True,
 ("'2020/12/04'",
  np.int64(175)):    Duration          Date  Pulse  Maxpulse  Calories  Random
 3      45.0  '2020/12/04'    109       175     282.4    True,
 ("'2020/12/05'",
  np.int64(148)):    Duration          Date  Pulse  Maxpulse  Calories  Random
 4      45.0  '2020/12/05'    117       148     406.0    True}

In [28]:
 df4g = df3.groupby('Pulse').get_group(117)

In [29]:
df4g.sum()

Duration                        45.0
Date        '2020/12/02''2020/12/05'
Pulse                            234
Maxpulse                         293
Calories                       885.0
Random                             2
dtype: object

In [34]:
df4g.drop(['Duration', 'Random', 'Date'], axis=1).mean()

Pulse       117.0
Maxpulse    146.5
Calories    442.5
dtype: float64

In [35]:
df4g.describe()

       Duration  Pulse   Maxpulse    Calories
count       1.0    2.0    2.00000    2.000000
mean       45.0  117.0  146.50000  442.500000
std         NaN    0.0    2.12132   51.618795
min        45.0  117.0  145.00000  406.000000
25%        45.0  117.0  145.75000  424.250000
50%        45.0  117.0  146.50000  442.500000
75%        45.0  117.0  147.25000  460.750000
max        45.0  117.0  148.00000  479.000000

In [36]:
df4g.drop(['Duration', 'Random', 'Date'], axis=1).agg(['sum', 'max', 'mean'])

      Pulse  Maxpulse  Calories
sum   234.0     293.0     885.0
max   117.0     148.0     479.0
mean  117.0     146.5     442.5

In [39]:
df = pd.DataFrame({'ID': [1,2,3,4,5], 'Name': ["Ajay", 'Ajay2', "Name", "Nein", "Heil H1tle4"]})
df

   ID         Name
0   1         Ajay
1   2        Ajay2
2   3         Name
3   4         Nein
4   5  Heil H1tle4

In [42]:
list(df.groupby(by='Name'))

[('Ajay',
     ID  Name
  0   1  Ajay),
 ('Ajay2',
     ID   Name
  1   2  Ajay2),
 ('Heil H1tle4',
     ID         Name
  4   5  Heil H1tle4),
 ('Name',
     ID  Name
  2   3  Name),
 ('Nein',
     ID  Name
  3   4  Nein)]

In [45]:
df2 = pd.DataFrame({'ID': [1,2,3,4,5], 'Name': ["Ajay", 'Ajay2', "Name", "Nein", "Heil H1tle4x"]})
df2

   ID          Name
0   1          Ajay
1   2         Ajay2
2   3          Name
3   4          Nein
4   5  Heil H1tle4x

In [46]:
pd.merge(df, df2)

   ID   Name
0   1   Ajay
1   2  Ajay2
2   3   Name
3   4   Nein

In [47]:
pd.merge(df, df2, on='ID')

   ID       Name_x        Name_y
0   1         Ajay          Ajay
1   2        Ajay2         Ajay2
2   3         Name          Name
3   4         Nein          Nein
4   5  Heil H1tle4  Heil H1tle4x

In [48]:
pd.merge(df, df2, on='Name')

   ID_x   Name  ID_y
0     1   Ajay     1
1     2  Ajay2     2
2     3   Name     3
3     4   Nein     4

In [49]:
pd.merge(df, df2, on='Name', how='left')

   ID_x         Name  ID_y
0     1         Ajay   1.0
1     2        Ajay2   2.0
2     3         Name   3.0
3     4         Nein   4.0
4     5  Heil H1tle4   NaN

In [50]:
pd.merge(df, df2, on='Name', how='right')

   ID_x          Name  ID_y
0   1.0          Ajay     1
1   2.0         Ajay2     2
2   3.0          Name     3
3   4.0          Nein     4
4   NaN  Heil H1tle4x     5

In [52]:
pd.merge(df, df2, how='outer', indicator=True)

   ID          Name      _merge
0   1          Ajay        both
1   2         Ajay2        both
2   3          Name        both
3   4          Nein        both
4   5   Heil H1tle4   left_only
5   5  Heil H1tle4x  right_only

In [55]:
pd.merge(df, df2, how='outer', indicator=True, left_index=True, right_index=True)

   ID_x       Name_x  ID_y        Name_y _merge
0     1         Ajay     1          Ajay   both
1     2        Ajay2     2         Ajay2   both
2     3         Name     3          Name   both
3     4         Nein     4          Nein   both
4     5  Heil H1tle4     5  Heil H1tle4x   both

In [63]:
pd_dict = {
    'Name': ['Ajay', 'Xajay', 'BTCUSD', 'ETHUSD'],
    'Age': [18,81,23,42]
}
df = pd.DataFrame(
    pd_dict,
    index=['Emp1', 'Emp2', 'Emp3', 'Emp4']
)

In [69]:
df1 = pd.DataFrame([{'Name': 'RTX', 'Age': 99}], index=['Emp5'])

In [70]:
pd.concat([df, df1])

        Name  Age
Emp1    Ajay   18
Emp2   Xajay   81
Emp3  BTCUSD   23
Emp4  ETHUSD   42
Emp5     RTX   99

In [78]:
df2 = pd.read_csv('dat.csv', index_col='Name')
df2

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [77]:
print(df2.to_string())

           Name     Type1     Type2  Height  Weight  Legendary
No
1     Bulbasaur     Grass    Poison     0.7     6.9          0
2       Ivysaur     Grass    Poison     1.0    13.0          0
3      Venusaur     Grass    Poison     2.0   100.0          0
4    Charmander      Fire       NaN     0.6     8.5          0
5    Charmeleon      Fire       NaN     1.1    19.0          0
6     Charizard      Fire    Flying     1.7    90.5          0
7      Squirtle     Water       NaN     0.5     9.0          0
8     Wartortle     Water       NaN     1.0    22.5          0
9     Blastoise     Water       NaN     1.6    85.5          0
10     Caterpie       Bug       NaN     0.3     2.9          0
11      Metapod       Bug       NaN     0.7     9.9          0
12   Butterfree       Bug    Flying     1.1    32.0          0
13       Weedle       Bug    Poison     0.3     3.2          0
14       Kakuna       Bug    Poison     0.6    10.0          0
15     Beedrill       Bug    Poison     1.0    29.5          0
16       Pidgey    Normal    Flying     0.3     1.8          0
17    Pidgeotto    Normal    Flying     1.1    30.0          0
18      Pidgeot    Normal    Flying     1.5    39.5          0
19      Rattata    Normal       NaN     0.3     3.5          0
20     Raticate    Normal       NaN     0.7    18.5          0
21      Spearow    Normal    Flying     0.3     2.0          0
22       Fearow    Normal    Flying     1.2    38.0          0
23        Ekans    Poison       NaN     2.0     6.9          0
24        Arbok    Poison       NaN     3.5    65.0          0
25      Pikachu  Electric       NaN     0.4     6.0          0
26       Raichu  Electric       NaN     0.8    30.0          0
27    Sandshrew    Ground       NaN     0.6    12.0          0
28    Sandslash    Ground       NaN     1.0    29.5          0
29     Nidoran♀    Poison       NaN     0.4     7.0          0
30     Nidorina    Poison       NaN     0.8    20.0          0
31    Nidoqueen    Poison    Ground     1.3    60.0          0
32     Nidoran♂    Poison       NaN     0.5     9.0          0
33     Nidorino    Poison       NaN     0.9    19.5          0
34     Nidoking    Poison    Ground     1.4    62.0          0
35     Clefairy     Fairy       NaN     0.6     7.5          0
36     Clefable     Fairy       NaN     1.3    40.0          0
37       Vulpix      Fire       NaN     0.6     9.9          0
38    Ninetales      Fire       NaN     1.1    19.9          0
39   Jigglypuff    Normal     Fairy     0.5     5.5          0
40   Wigglytuff    Normal     Fairy     1.0    12.0          0
41        Zubat    Poison    Flying     0.8     7.5          0
42       Golbat    Poison    Flying     1.6    55.0          0
43       Oddish     Grass    Poison     0.5     5.4          0
44        Gloom     Grass    Poison     0.8     8.6          0
45    Vileplume     Grass    Poison     1.2    18.6          0
46        Paras       Bug     Grass     0.3     5.4          0
47     Parasect       Bug     Grass     1.0    29.5          0
48      Venonat       Bug    Poison     1.0    30.0          0
49     Venomoth       Bug    Poison     1.5    12.5          0
50      Diglett    Ground       NaN     0.2     0.8          0
51      Dugtrio    Ground       NaN     0.7    33.3          0
52       Meowth    Normal       NaN     0.4     4.2          0
53      Persian    Normal       NaN     1.0    32.0          0
54      Psyduck     Water       NaN     0.8    19.6          0
55      Golduck     Water       NaN     1.7    76.6          0
56       Mankey  Fighting       NaN     0.5    28.0          0
57     Primeape  Fighting       NaN     1.0    32.0          0
58    Growlithe      Fire       NaN     0.7    19.0          0
59     Arcanine      Fire       NaN     1.9   155.0          0
60      Poliwag     Water       NaN     0.6    12.4          0
61    Poliwhirl     Water       NaN     1.0    20.0          0
62    Poliwrath     Water  Fighting     1.3    54.0          0
63         Abra   Psychic       NaN     0.9    19.5          0
64      Kadabra   Psychic       NaN     1.3    56.5          0
65     Alakazam   Psychic       NaN     1.5    48.0          0
66       Machop  Fighting       NaN     0.8    19.5          0
67      Machoke  Fighting       NaN     1.5    70.5          0
68      Machamp  Fighting       NaN     1.6   130.0          0
69   Bellsprout     Grass    Poison     0.7     4.0          0
70   Weepinbell     Grass    Poison     1.0     6.4          0
71   Victreebel     Grass    Poison     1.7    15.5          0
72    Tentacool     Water    Poison     0.9    45.5          0
73   Tentacruel     Water    Poison     1.6    55.0          0
74      Geodude      Rock    Ground     0.4    20.0          0
75     Graveler      Rock    Ground     1.0   105.0          0
76        Golem      Rock    Ground     1.4   300.0          0
77       Ponyta      Fire       NaN     1.0    30.0          0
78     Rapidash      Fire       NaN     1.7    95.0          0
79     Slowpoke     Water   Psychic     1.2    36.0          0
80      Slowbro     Water   Psychic     1.6    78.5          0
81    Magnemite  Electric     Steel     0.3     6.0          0
82     Magneton  Electric     Steel     1.0    60.0          0
83   Farfetch'd    Normal    Flying     0.8    15.0          0
84        Doduo    Normal    Flying     1.4    39.2          0
85       Dodrio    Normal    Flying     1.8    85.2          0
86         Seel     Water       NaN     1.1    90.0          0
87      Dewgong     Water       Ice     1.7   120.0          0
88       Grimer    Poison       NaN     0.9    30.0          0
89          Muk    Poison       NaN     1.2    30.0          0
90     Shellder     Water       NaN     0.3     4.0          0
91     Cloyster     Water       Ice     1.5   132.5          0
92       Gastly     Ghost    Poison     1.3     0.1          0
93      Haunter     Ghost    Poison     1.6     0.1          0
94       Gengar     Ghost    Poison     1.5    40.5          0
95         Onix      Rock    Ground     8.8   210.0          0
96      Drowzee   Psychic       NaN     1.0    32.4          0
97        Hypno   Psychic       NaN     1.6    75.6          0
98       Krabby     Water       NaN     0.4     6.5          0
99      Kingler     Water       NaN     1.3    60.0          0
100     Voltorb  Electric       NaN     0.5    10.4          0
101   Electrode  Electric       NaN     1.2    66.6          0
102   Exeggcute     Grass   Psychic     0.4     2.5          0
103   Exeggutor     Grass   Psychic     2.0   120.0          0
104      Cubone    Ground       NaN     0.4     6.5          0
105     Marowak    Ground       NaN     1.0    45.0          0
106   Hitmonlee  Fighting       NaN     1.5    49.8          0
107  Hitmonchan  Fighting       NaN     1.4    50.2          0
108   Lickitung    Normal       NaN     1.2    65.5          0
109     Koffing    Poison       NaN     0.6     1.0          0
110     Weezing    Poison       NaN     1.2     9.5          0
111     Rhyhorn    Ground      Rock     1.0   115.0          0
112      Rhydon    Ground      Rock     1.9   120.0          0
113     Chansey    Normal       NaN     1.1    34.6          0
114     Tangela     Grass       NaN     1.0    35.0          0
115  Kangaskhan    Normal       NaN     2.2    80.0          0
116      Horsea     Water       NaN     0.4     8.0          0
117      Seadra     Water       NaN     1.2    25.0          0
118     Goldeen     Water       NaN     0.6    15.0          0
119     Seaking     Water       NaN     1.3    39.0          0
120      Staryu     Water       NaN     0.8    34.5          0
121     Starmie     Water   Psychic     1.1    80.0          0
122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
123     Scyther       Bug    Flying     1.5    56.0          0
124        Jynx       Ice   Psychic     1.4    40.6          0
125  Electabuzz  Electric       NaN     1.1    30.0          0
126      Magmar      Fire       NaN     1.3    44.5          0
127      Pinsir       Bug       NaN     1.5    55.0          0
128      Tauros    Normal       NaN     1.4    88.4          0
129    Magikarp     Water       NaN     0.9    10.0          0
130    Gyarados     Water    Flying     6.5   235.0          0
131      Lapras     Water       Ice     2.5   220.0          0
132       Ditto    Normal       NaN     0.3     4.0          0
133       Eevee    Normal       NaN     0.3     6.5          0
134    Vaporeon     Water       NaN     1.0    29.0          0
135     Jolteon  Electric       NaN     0.8    24.5          0
136     Flareon      Fire       NaN     0.9    25.0          0
137     Porygon    Normal       NaN     0.8    36.5          0
138     Omanyte      Rock     Water     0.4     7.5          0
139     Omastar      Rock     Water     1.0    35.0          0
140      Kabuto      Rock     Water     0.5    11.5          0
141    Kabutops      Rock     Water     1.3    40.5          0
142  Aerodactyl      Rock    Flying     1.8    59.0          0
143     Snorlax    Normal       NaN     2.1   460.0          0
144    Articuno       Ice    Flying     1.7    55.4          1
145      Zapdos  Electric    Flying     1.6    52.6          1
146     Moltres      Fire    Flying     2.0    60.0          1
147     Dratini    Dragon       NaN     1.8     3.3          0
148   Dragonair    Dragon       NaN     4.0    16.5          0
149   Dragonite    Dragon    Flying     2.2   210.0          0
150      Mewtwo   Psychic       NaN     2.0   122.0          1

In [80]:
df2.loc[['Bulbasaur']]

           No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur   1  Grass  Poison     0.7     6.9          0

In [81]:
df2.iloc[3:7, 1:3]

            Type1   Type2
Name
Charmander   Fire     NaN
Charmeleon   Fire     NaN
Charizard    Fire  Flying
Squirtle    Water     NaN

In [83]:
df2.loc[df2['Weight'] > 50]

             No     Type1     Type2  Height  Weight  Legendary
Name
Venusaur      3     Grass    Poison     2.0   100.0          0
Charizard     6      Fire    Flying     1.7    90.5          0
Blastoise     9     Water       NaN     1.6    85.5          0
Arbok        24    Poison       NaN     3.5    65.0          0
Nidoqueen    31    Poison    Ground     1.3    60.0          0
Nidoking     34    Poison    Ground     1.4    62.0          0
Golbat       42    Poison    Flying     1.6    55.0          0
Golduck      55     Water       NaN     1.7    76.6          0
Arcanine     59      Fire       NaN     1.9   155.0          0
Poliwrath    62     Water  Fighting     1.3    54.0          0
Kadabra      64   Psychic       NaN     1.3    56.5          0
Machoke      67  Fighting       NaN     1.5    70.5          0
Machamp      68  Fighting       NaN     1.6   130.0          0
Tentacruel   73     Water    Poison     1.6    55.0          0
Graveler     75      Rock    Ground     1.0   105.0          0
Golem        76      Rock    Ground     1.4   300.0          0
Rapidash     78      Fire       NaN     1.7    95.0          0
Slowbro      80     Water   Psychic     1.6    78.5          0
Magneton     82  Electric     Steel     1.0    60.0          0
Dodrio       85    Normal    Flying     1.8    85.2          0
Seel         86     Water       NaN     1.1    90.0          0
Dewgong      87     Water       Ice     1.7   120.0          0
Cloyster     91     Water       Ice     1.5   132.5          0
Onix         95      Rock    Ground     8.8   210.0          0
Hypno        97   Psychic       NaN     1.6    75.6          0
Kingler      99     Water       NaN     1.3    60.0          0
Electrode   101  Electric       NaN     1.2    66.6          0
Exeggutor   103     Grass   Psychic     2.0   120.0          0
Hitmonchan  107  Fighting       NaN     1.4    50.2          0
Lickitung   108    Normal       NaN     1.2    65.5          0
Rhyhorn     111    Ground      Rock     1.0   115.0          0
Rhydon      112    Ground      Rock     1.9   120.0          0
Kangaskhan  115    Normal       NaN     2.2    80.0          0
Starmie     121     Water   Psychic     1.1    80.0          0
Mr. Mime    122   Psychic     Fairy     1.3    54.5          0
Scyther     123       Bug    Flying     1.5    56.0          0
Pinsir      127       Bug       NaN     1.5    55.0          0
Tauros      128    Normal       NaN     1.4    88.4          0
Gyarados    130     Water    Flying     6.5   235.0          0
Lapras      131     Water       Ice     2.5   220.0          0
Aerodactyl  142      Rock    Flying     1.8    59.0          0
Snorlax     143    Normal       NaN     2.1   460.0          0
Articuno    144       Ice    Flying     1.7    55.4          1
Zapdos      145  Electric    Flying     1.6    52.6          1
Moltres     146      Fire    Flying     2.0    60.0          1
Dragonite   149    Dragon    Flying     2.2   210.0          0
Mewtwo      150   Psychic       NaN     2.0   122.0          1

In [87]:
df2.loc[df2['Type1'] == 'Poison']

            No   Type1   Type2  Height  Weight  Legendary
Name
Ekans       23  Poison     NaN     2.0     6.9          0
Arbok       24  Poison     NaN     3.5    65.0          0
Nidoran♀    29  Poison     NaN     0.4     7.0          0
Nidorina    30  Poison     NaN     0.8    20.0          0
Nidoqueen   31  Poison  Ground     1.3    60.0          0
Nidoran♂    32  Poison     NaN     0.5     9.0          0
Nidorino    33  Poison     NaN     0.9    19.5          0
Nidoking    34  Poison  Ground     1.4    62.0          0
Zubat       41  Poison  Flying     0.8     7.5          0
Golbat      42  Poison  Flying     1.6    55.0          0
Grimer      88  Poison     NaN     0.9    30.0          0
Muk         89  Poison     NaN     1.2    30.0          0
Koffing    109  Poison     NaN     0.6     1.0          0
Weezing    110  Poison     NaN     1.2     9.5          0

In [97]:
df2.loc[(df2['Type1'] == 'Poison') & (df2['Type2'].notnull())]

           No   Type1   Type2  Height  Weight  Legendary
Name
Nidoqueen  31  Poison  Ground     1.3    60.0          0
Nidoking   34  Poison  Ground     1.4    62.0          0
Zubat      41  Poison  Flying     0.8     7.5          0
Golbat     42  Poison  Flying     1.6    55.0          0

In [98]:
df2.loc[(df2['Type1'] == 'Poison') | (df2['Type2'].notnull())]

             No     Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1     Grass  Poison     0.7     6.9          0
Ivysaur       2     Grass  Poison     1.0    13.0          0
Venusaur      3     Grass  Poison     2.0   100.0          0
Charizard     6      Fire  Flying     1.7    90.5          0
Butterfree   12       Bug  Flying     1.1    32.0          0
...         ...       ...     ...     ...     ...        ...
Aerodactyl  142      Rock  Flying     1.8    59.0          0
Articuno    144       Ice  Flying     1.7    55.4          1
Zapdos      145  Electric  Flying     1.6    52.6          1
Moltres     146      Fire  Flying     2.0    60.0          1
Dragonite   149    Dragon  Flying     2.2   210.0          0

[77 rows x 6 columns]

In [99]:
df2.mean(numeric_only=True)

No           75.500000
Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64

In [101]:
df2.sum(numeric_only=True).sum()

np.float64(18443.7)

In [102]:
df2.min(numeric_only=True)

No           1.0
Height       0.2
Weight       0.1
Legendary    0.0
dtype: float64

In [103]:
df2.max(numeric_only=True)

No           150.0
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64

In [105]:
df2.count()

No           150
Type1        150
Type2         67
Height       150
Weight       150
Legendary    150
dtype: int64

In [106]:
df2['Height'].mean()

np.float64(1.2)

In [107]:
df2['Weight'].mean()

np.float64(46.23133333333334)

In [111]:
dict(list(df2.groupby('Type1')))

{'Bug':              No Type1   Type2  Height  Weight  Legendary
 Name
 Caterpie     10   Bug     NaN     0.3     2.9          0
 Metapod      11   Bug     NaN     0.7     9.9          0
 Butterfree   12   Bug  Flying     1.1    32.0          0
 Weedle       13   Bug  Poison     0.3     3.2          0
 Kakuna       14   Bug  Poison     0.6    10.0          0
 Beedrill     15   Bug  Poison     1.0    29.5          0
 Paras        46   Bug   Grass     0.3     5.4          0
 Parasect     47   Bug   Grass     1.0    29.5          0
 Venonat      48   Bug  Poison     1.0    30.0          0
 Venomoth     49   Bug  Poison     1.5    12.5          0
 Scyther     123   Bug  Flying     1.5    56.0          0
 Pinsir      127   Bug     NaN     1.5    55.0          0,
 'Dragon':             No   Type1   Type2  Height  Weight  Legendary
 Name
 Dratini    147  Dragon     NaN     1.8     3.3          0
 Dragonair  148  Dragon     NaN     4.0    16.5          0
 Dragonite  149  Dragon  Flying     2.2   210.0          0,
 'Electric':              No     Type1   Type2  Height  Weight  Legendary
 Name
 Pikachu      25  Electric     NaN     0.4     6.0          0
 Raichu       26  Electric     NaN     0.8    30.0          0
 Magnemite    81  Electric   Steel     0.3     6.0          0
 Magneton     82  Electric   Steel     1.0    60.0          0
 Voltorb     100  Electric     NaN     0.5    10.4          0
 Electrode   101  Electric     NaN     1.2    66.6          0
 Electabuzz  125  Electric     NaN     1.1    30.0          0
 Jolteon     135  Electric     NaN     0.8    24.5          0
 Zapdos      145  Electric  Flying     1.6    52.6          1,
 'Fairy':           No  Type1 Type2  Height  Weight  Legendary
 Name
 Clefairy  35  Fairy   NaN     0.6     7.5          0
 Clefable  36  Fairy   NaN     1.3    40.0          0,
 'Fighting':              No     Type1 Type2  Height  Weight  Legendary
 Name
 Mankey       56  Fighting   NaN     0.5    28.0          0
 Primeape     57  Fighting   NaN     1.0    32.0          0
 Machop       66  Fighting   NaN     0.8    19.5          0
 Machoke      67  Fighting   NaN     1.5    70.5          0
 Machamp      68  Fighting   NaN     1.6   130.0          0
 Hitmonlee   106  Fighting   NaN     1.5    49.8          0
 Hitmonchan  107  Fighting   NaN     1.4    50.2          0,
 'Fire':              No Type1   Type2  Height  Weight  Legendary
 Name
 Charmander    4  Fire     NaN     0.6     8.5          0
 Charmeleon    5  Fire     NaN     1.1    19.0          0
 Charizard     6  Fire  Flying     1.7    90.5          0
 Vulpix       37  Fire     NaN     0.6     9.9          0
 Ninetales    38  Fire     NaN     1.1    19.9          0
 Growlithe    58  Fire     NaN     0.7    19.0          0
 Arcanine     59  Fire     NaN     1.9   155.0          0
 Ponyta       77  Fire     NaN     1.0    30.0          0
 Rapidash     78  Fire     NaN     1.7    95.0          0
 Magmar      126  Fire     NaN     1.3    44.5          0
 Flareon     136  Fire     NaN     0.9    25.0          0
 Moltres     146  Fire  Flying     2.0    60.0          1,
 'Ghost':          No  Type1   Type2  Height  Weight  Legendary
 Name
 Gastly   92  Ghost  Poison     1.3     0.1          0
 Haunter  93  Ghost  Poison     1.6     0.1          0
 Gengar   94  Ghost  Poison     1.5    40.5          0,
 'Grass':              No  Type1    Type2  Height  Weight  Legendary
 Name
 Bulbasaur     1  Grass   Poison     0.7     6.9          0
 Ivysaur       2  Grass   Poison     1.0    13.0          0
 Venusaur      3  Grass   Poison     2.0   100.0          0
 Oddish       43  Grass   Poison     0.5     5.4          0
 Gloom        44  Grass   Poison     0.8     8.6          0
 Vileplume    45  Grass   Poison     1.2    18.6          0
 Bellsprout   69  Grass   Poison     0.7     4.0          0
 Weepinbell   70  Grass   Poison     1.0     6.4          0
 Victreebel   71  Grass   Poison     1.7    15.5          0
 Exeggcute   102  Grass  Psychic     0.4     2.5          0
 Exeggutor   103  Grass  Psychic     2.0   120.0          0
 Tangela     114  Grass      NaN     1.0    35.0          0,
 'Ground':             No   Type1 Type2  Height  Weight  Legendary
 Name
 Sandshrew   27  Ground   NaN     0.6    12.0          0
 Sandslash   28  Ground   NaN     1.0    29.5          0
 Diglett     50  Ground   NaN     0.2     0.8          0
 Dugtrio     51  Ground   NaN     0.7    33.3          0
 Cubone     104  Ground   NaN     0.4     6.5          0
 Marowak    105  Ground   NaN     1.0    45.0          0
 Rhyhorn    111  Ground  Rock     1.0   115.0          0
 Rhydon     112  Ground  Rock     1.9   120.0          0,
 'Ice':            No Type1    Type2  Height  Weight  Legendary
 Name
 Jynx      124   Ice  Psychic     1.4    40.6          0
 Articuno  144   Ice   Flying     1.7    55.4          1,
 'Normal':              No   Type1   Type2  Height  Weight  Legendary
 Name
 Pidgey       16  Normal  Flying     0.3     1.8          0
 Pidgeotto    17  Normal  Flying     1.1    30.0          0
 Pidgeot      18  Normal  Flying     1.5    39.5          0
 Rattata      19  Normal     NaN     0.3     3.5          0
 Raticate     20  Normal     NaN     0.7    18.5          0
 Spearow      21  Normal  Flying     0.3     2.0          0
 Fearow       22  Normal  Flying     1.2    38.0          0
 Jigglypuff   39  Normal   Fairy     0.5     5.5          0
 Wigglytuff   40  Normal   Fairy     1.0    12.0          0
 Meowth       52  Normal     NaN     0.4     4.2          0
 Persian      53  Normal     NaN     1.0    32.0          0
 Farfetch'd   83  Normal  Flying     0.8    15.0          0
 Doduo        84  Normal  Flying     1.4    39.2          0
 Dodrio       85  Normal  Flying     1.8    85.2          0
 Lickitung   108  Normal     NaN     1.2    65.5          0
 Chansey     113  Normal     NaN     1.1    34.6          0
 Kangaskhan  115  Normal     NaN     2.2    80.0          0
 Tauros      128  Normal     NaN     1.4    88.4          0
 Ditto       132  Normal     NaN     0.3     4.0          0
 Eevee       133  Normal     NaN     0.3     6.5          0
 Porygon     137  Normal     NaN     0.8    36.5          0
 Snorlax     143  Normal     NaN     2.1   460.0          0,
 'Poison':             No   Type1   Type2  Height  Weight  Legendary
 Name
 Ekans       23  Poison     NaN     2.0     6.9          0
 Arbok       24  Poison     NaN     3.5    65.0          0
 Nidoran♀    29  Poison     NaN     0.4     7.0          0
 Nidorina    30  Poison     NaN     0.8    20.0          0
 Nidoqueen   31  Poison  Ground     1.3    60.0          0
 Nidoran♂    32  Poison     NaN     0.5     9.0          0
 Nidorino    33  Poison     NaN     0.9    19.5          0
 Nidoking    34  Poison  Ground     1.4    62.0          0
 Zubat       41  Poison  Flying     0.8     7.5          0
 Golbat      42  Poison  Flying     1.6    55.0          0
 Grimer      88  Poison     NaN     0.9    30.0          0
 Muk         89  Poison     NaN     1.2    30.0          0
 Koffing    109  Poison     NaN     0.6     1.0          0
 Weezing    110  Poison     NaN     1.2     9.5          0,
 'Psychic':            No    Type1  Type2  Height  Weight  Legendary
 Name
 Abra       63  Psychic    NaN     0.9    19.5          0
 Kadabra    64  Psychic    NaN     1.3    56.5          0
 Alakazam   65  Psychic    NaN     1.5    48.0          0
 Drowzee    96  Psychic    NaN     1.0    32.4          0
 Hypno      97  Psychic    NaN     1.6    75.6          0
 Mr. Mime  122  Psychic  Fairy     1.3    54.5          0
 Mewtwo    150  Psychic    NaN     2.0   122.0          1,
 'Rock':              No Type1   Type2  Height  Weight  Legendary
 Name
 Geodude      74  Rock  Ground     0.4    20.0          0
 Graveler     75  Rock  Ground     1.0   105.0          0
 Golem        76  Rock  Ground     1.4   300.0          0
 Onix         95  Rock  Ground     8.8   210.0          0
 Omanyte     138  Rock   Water     0.4     7.5          0
 Omastar     139  Rock   Water     1.0    35.0          0
 Kabuto      140  Rock   Water     0.5    11.5          0
 Kabutops    141  Rock   Water     1.3    40.5          0
 Aerodactyl  142  Rock  Flying     1.8    59.0          0,
 'Water':              No  Type1     Type2  Height  Weight  Legendary
 Name
 Squirtle      7  Water       NaN     0.5     9.0          0
 Wartortle     8  Water       NaN     1.0    22.5          0
 Blastoise     9  Water       NaN     1.6    85.5          0
 Psyduck      54  Water       NaN     0.8    19.6          0
 Golduck      55  Water       NaN     1.7    76.6          0
 Poliwag      60  Water       NaN     0.6    12.4          0
 Poliwhirl    61  Water       NaN     1.0    20.0          0
 Poliwrath    62  Water  Fighting     1.3    54.0          0
 Tentacool    72  Water    Poison     0.9    45.5          0
 Tentacruel   73  Water    Poison     1.6    55.0          0
 Slowpoke     79  Water   Psychic     1.2    36.0          0
 Slowbro      80  Water   Psychic     1.6    78.5          0
 Seel         86  Water       NaN     1.1    90.0          0
 Dewgong      87  Water       Ice     1.7   120.0          0
 Shellder     90  Water       NaN     0.3     4.0          0
 Cloyster     91  Water       Ice     1.5   132.5          0
 Krabby       98  Water       NaN     0.4     6.5          0
 Kingler      99  Water       NaN     1.3    60.0          0
 Horsea      116  Water       NaN     0.4     8.0          0
 Seadra      117  Water       NaN     1.2    25.0          0
 Goldeen     118  Water       NaN     0.6    15.0          0
 Seaking     119  Water       NaN     1.3    39.0          0
 Staryu      120  Water       NaN     0.8    34.5          0
 Starmie     121  Water   Psychic     1.1    80.0          0
 Magikarp    129  Water       NaN     0.9    10.0          0
 Gyarados    130  Water    Flying     6.5   235.0          0
 Lapras      131  Water       Ice     2.5   220.0          0
 Vaporeon    134  Water       NaN     1.0    29.0          0}

In [113]:
print(df2.groupby('Type1')['Height'].mean())

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [114]:
df2.groupby('Type1')['Height'].mean()

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [117]:
df = pd.read_csv('dat.csv')
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [118]:
df.drop(columns=['Legendary'])

      No        Name    Type1   Type2  Height  Weight
0      1   Bulbasaur    Grass  Poison     0.7     6.9
1      2     Ivysaur    Grass  Poison     1.0    13.0
2      3    Venusaur    Grass  Poison     2.0   100.0
3      4  Charmander     Fire     NaN     0.6     8.5
4      5  Charmeleon     Fire     NaN     1.1    19.0
..   ...         ...      ...     ...     ...     ...
145  146     Moltres     Fire  Flying     2.0    60.0
146  147     Dratini   Dragon     NaN     1.8     3.3
147  148   Dragonair   Dragon     NaN     4.0    16.5
148  149   Dragonite   Dragon  Flying     2.2   210.0
149  150      Mewtwo  Psychic     NaN     2.0   122.0

[150 rows x 6 columns]

In [120]:
df.dropna(subset=['Type2'])

      No        Name     Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass  Poison     0.7     6.9          0
1      2     Ivysaur     Grass  Poison     1.0    13.0          0
2      3    Venusaur     Grass  Poison     2.0   100.0          0
5      6   Charizard      Fire  Flying     1.7    90.5          0
11    12  Butterfree       Bug  Flying     1.1    32.0          0
..   ...         ...       ...     ...     ...     ...        ...
141  142  Aerodactyl      Rock  Flying     1.8    59.0          0
143  144    Articuno       Ice  Flying     1.7    55.4          1
144  145      Zapdos  Electric  Flying     1.6    52.6          1
145  146     Moltres      Fire  Flying     2.0    60.0          1
148  149   Dragonite    Dragon  Flying     2.2   210.0          0

[67 rows x 7 columns]

In [122]:
df.fillna({'Type2': 'None'})

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire    None     0.6     8.5          0
4      5  Charmeleon     Fire    None     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon    None     1.8     3.3          0
147  148   Dragonair   Dragon    None     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic    None     2.0   122.0          1

[150 rows x 7 columns]

In [123]:
df['Type1'].replace({'Grass': 'GRASS'})

0        GRASS
1        GRASS
2        GRASS
3         Fire
4         Fire
        ...
145       Fire
146     Dragon
147     Dragon
148     Dragon
149    Psychic
Name: Type1, Length: 150, dtype: object

In [126]:
df['Type1'].replace({'Fire': "FIRE"})

0        Grass
1        Grass
2        Grass
3         FIRE
4         FIRE
        ...
145       FIRE
146     Dragon
147     Dragon
148     Dragon
149    Psychic
Name: Type1, Length: 150, dtype: object

In [128]:
df['Type1'].replace({'Fire': 'FUIre',
                    'Grass':'Gerass'},
                   )

0       Gerass
1       Gerass
2       Gerass
3        FUIre
4        FUIre
        ...
145      FUIre
146     Dragon
147     Dragon
148     Dragon
149    Psychic
Name: Type1, Length: 150, dtype: object

In [129]:
df['Name'].str.lower()

0       bulbasaur
1         ivysaur
2        venusaur
3      charmander
4      charmeleon
          ...
145       moltres
146       dratini
147     dragonair
148     dragonite
149        mewtwo
Name: Name, Length: 150, dtype: object

In [131]:
df['Type1'].str.upper()

0        GRASS
1        GRASS
2        GRASS
3         FIRE
4         FIRE
        ...
145       FIRE
146     DRAGON
147     DRAGON
148     DRAGON
149    PSYCHIC
Name: Type1, Length: 150, dtype: object

In [132]:
df['Legendary'].astype(bool)

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146    False
147    False
148    False
149     True
Name: Legendary, Length: 150, dtype: bool

In [133]:
df.drop_duplicates()

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]